# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in google-apis.gemspec
gemspec


group :development do
  gem 'bundler', '~> 1.7'
  gem 'coveralls', '~> 0.8'
  gem 'dotenv', '~> 2.0'
  gem 'fakefs', '~> 0.6', require: 'fakefs/safe'
  gem 'google-id-token', '~> 1.3'
  gem 'json_spec', '~> 1.1'
  gem 'launchy', '~> 2.4'
  gem 'os', '~> 0.9'
  gem 'rake', '~> 11.2'
  gem 'redis', '~> 3.2'
  gem 'rmail', '~> 1.1'
  gem 'rspec', '~> 3.1'
  gem 'rubocop', '~> 0.42.0'
  gem 'simplecov', '~> 0.12'
  gem 'webmock', '~> 2.1'
end

platforms :jruby do
  group :development do
    gem 'jruby-openssl'
  end
end

platforms :ruby do
  group :development do
    gem 'github-markup', '~> 1.3'
    gem 'pry-byebug', '~> 3.2'
    gem 'pry-doc', '~> 0.8'
    gem 'redcarpet', '~> 3.2'
    gem 'yard', '~> 0.8'
  end
end

platforms :mri_21, :mri_22, :mri_23 do
  group :development do
    gem 'derailed_benchmarks'
    gem 'rack-test'
    gem 'stackprof'
  end
end

gem 'rails', ENV['RAILS_VERSION'] if ENV['RAILS_VERSION']
